### ISSUE TITLE
Undefined variable: instanceId

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/richdocuments#218]
```
ErrorException: Undefined variable: instanceId
#12 richdocuments/lib/helper.php(43): handleError
#11 richdocuments/lib/helper.php(43): parseFileId
#10 richdocuments/controller/documentcontroller.php(482): wopiGetToken
#9 richdocuments/controller/documentcontroller.php(341): index
#8 richdocuments/controller/documentcontroller.php(0): call_user_func_array
#7 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): executeController
#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): dispatch
#5 /var/www/owncloud/lib/private/AppFramework/App.php(103): main
#4 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): __invoke
#3 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(919): handleRequest
#0 /var/www/owncloud/index.php(55): null
```

Looking at https://github.com/owncloud/richdocuments/blob/master/lib/helper.php#L27-L45 - in the first if, the `$instanceId` is not set and the return thus creates this error

**Comment by jrevillard** [comment]
Any workaround for it ? I'm using the latest Owncloud docker image

**Comment by thebearon** [comment]
I haven't encountered this bug before. Have you got repro steps? Anything specific about the files in particular?

**Comment by jrevillard** [comment]
No, regular docker owncloud (10.0). I applied the following NextCloud fix and it worked: https://github.com/nextcloud/richdocuments/issues/68
